---
title: "tables"
author: "Caitlin Sarro"
date: "3/30/2022"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("")

#choose which one to include, gridExtra, cowplot, or patchwork
packages = c('tidyverse', 'tidytext', 'dplyr', 'ggplot2','plyr','gridExtra','ggpubr','reshape2', 'ggrepel','ggstatsplot')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}

```
```{r}
#tips to help remember: https://r-charts.com/part-whole/donut-chart-ggplot2/
#import final data
final_coded_dataset <- read_csv("data/final_coded_dataset.csv")
```

```{r}


freq_table_charts <- count(final_coded_dataset, 'category')
as.numeric(freq_table_charts$freq)
freq_table_charts$perc <- freq_table_charts$freq / 211 *100

hsize <- 2

freq_table_charts %>% 
  mutate(x = hsize)

freq_table_charts$category[freq_table_charts$category == "democratic institutions"] <-"Democratic Institutions"
freq_table_charts$category[freq_table_charts$category == "participation"] <-"Participation"
freq_table_charts$category[freq_table_charts$category == "policy coherence"] <-"Policy Coherence"
freq_table_charts$category[freq_table_charts$category == "reflexivity and adaptation"] <-"Reflexivity & Adaptation"

freq_table_charts$category

#ggplot(freq_table_charts, aes(x = category, y = freq, fill = category)) +
#  geom_col(color = "black") +
#  coord_polar(theta = "y") +
#  guides(fill = guide_legend(title = "Title"))

freq_table_charts$category <- factor(freq_table_charts$category, levels = c("Participation", "Policy Coherence", "Democratic Institutions", "Reflexivity & Adaptation"))
freq_table_charts
ggplot(freq_table_charts, aes(x = hsize, y = perc, fill = category)) +
  geom_col(color = "black") +
  geom_col() +
  geom_text(aes(label = sprintf("%0.1f %%", perc)),
             position = position_stack(vjust = 0.5),  size=5) +
  coord_polar(theta = "y") +
  scale_fill_brewer(palette = "GnBu") +
  guides(fill = guide_legend(title = "Distribution of Sustainable \nGovernance Categories in \ntraining courses (N = 211)")) +
  coord_polar(theta = "y") +
  xlim(c(0.2, hsize + 0.5)) +
  theme(panel.background = element_rect(fill = 'white', colour = 'white'),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank()) 

```


```{r}
#weighted_freq_table <- read_csv("data/weighted_freq_table.csv")


un <- c(3.4166666, 2.16666666, 2.94999999, 2.25)
public_university <- c(5.50, 4.17, 9.03, 8.75)
private_university	<- c(4.08, 2.67, 6.62, 2.25)
civil_society <- c(4.50, 1.67, 3.20, 2.75)
research_business <- c(4.08, 1.17, 7.62, 8.00)
government <- c(2.42, 2.17, 1.58, 13.00)
UN_ONLY<- c(16.00,14.00,28.00,47.00)
NO_UN	<- c(20.58,11.83,28.05,34.75)
UN_UN_Partner	<- c(19.4166667,16.1666667,30.95,49.25)

weighted_freq_table <- rbind(un, public_university, private_university, civil_society, research_business, government, UN_ONLY, UN_UN_Partner)

colnames(weighted_freq_table)<- c("Participation","Policy\nCoherence","Democratic\nInstitutions","Reflexivity\n& Adaptation")

weighted_freq_table
#weighted_UN_freq_table <- rbind(un, UN_ONLY, NO_UN, UN_UN_Partner)

#toberevised <- list("Participation","Policy\nCoherence","Democratic\nInstitutions","Reflexivity\n& Adaptation")

weighted_freq_table_perc <- round(prop.table(as.matrix(weighted_freq_table),1),4)
#weighted_freq_table_perc <- round(prop.table(as.matrix(weighted_freq_table),1),2)


plot(weighted_freq_table_perc)

# transpose
long <- melt(weighted_freq_table_perc)
long

weighted <- dcast(long, Var2 ~ Var1)

weighted_un  <- weighted %>% select(Var2, UN_ONLY, un)

weighted_un <- weighted_un %>% 
  mutate(per_change = 
  (un - UN_ONLY))

weighted_un

```

```{r}
#un alone vs un with partners
p1_u <- ggplot(weighted_un, mapping=aes(x=Var2, 
      y=per_change)) +
        geom_col()  +
  geom_bar(stat="identity",fill="#95ccba") +
           scale_y_continuous(labels = scales::percent, limits = c(-.40,.40)) +
  labs(
    title = "UN Collaborative Authorship by Capacity",
    subtitle = "% of change from United Nations solo-authorship",
    x = NULL,
    y = "Training courses by author group"
  ) + theme(legend.position = "none") + theme_minimal()



p1_u
```


```{r}
#un aggregate vs government
weighted
weighted_gov  <- weighted %>% select(Var2, UN_UN_Partner, government)

weighted_gov <- weighted_gov %>% 
  mutate(per_change_g = 
  (government - UN_UN_Partner))

weighted_gov


p2_g <- ggplot(weighted_gov, mapping=aes(x=Var2, 
      y=per_change_g)) +
        geom_col() +
  geom_bar(stat="identity",fill="#e1b12d") +
           scale_y_continuous(labels = scales::percent, limits = c(-.40,.40)) +
  labs(
    title = "Government Authored Courses by Capacity",
    subtitle = "% of change from United Nations level",
    x = NULL,
    y = NULL
  )+ theme_minimal()

p2_g 

```




```{r}
#un aggregate vs pub uni vs private uni
weighted
weighted_uni  <- weighted %>% select(Var2, UN_UN_Partner, public_university, private_university)

weighted_uni <- weighted_uni %>% 
  mutate(per_change_pu = 
  (public_university - UN_UN_Partner)) %>% 
  mutate(per_change_pr = 
  (private_university - UN_UN_Partner))

weighted_uni




# Grouped
df_long <- pivot_longer(weighted_uni, per_change_pu:per_change_pr, names_to = "university", values_to = "perchang")  
df_long


#plot
p3_u <- ggplot(df_long, aes(fill=university, y=perchang, x=Var2)) + 
    geom_bar(position="stack", stat="identity") + 
  scale_fill_manual(labels = c("Public \nUniversity", "Private &\nUniversity"), values = c("per_change_pu" = "#a7ba42", "per_change_pr" = "#a4d8ff")) +
           scale_y_continuous(labels = scales::percent, limits = c(-.40,.40)) +
  labs(
    title = "University Authored Courses by Capacity",
    subtitle = "% of change from United Nations level",
    x = "Sustainable Governance Capacities",
    y = "Training courses by author group",
    fill = "Author Group"
  ) + theme(legend.position = "none") + theme_minimal()
p3_u
```


```{r}
#un aggregate vs research vs civil society
weighted
weighted_civ  <- weighted %>% select(Var2, UN_UN_Partner, civil_society, research_business)

weighted_civ <- weighted_civ %>% 
  mutate(per_change_ci = 
  (civil_society - UN_UN_Partner)) %>% 
  mutate(per_change_re = 
  (research_business - UN_UN_Partner))

weighted_civ




# Grouped
df_long <- pivot_longer(weighted_civ, per_change_ci:per_change_re, names_to = "org", values_to = "perchang")  
df_long

df_long
#plot
p4_c <- ggplot(df_long, aes(fill=org, y=perchang, x=Var2)) + 
    geom_bar(position="stack", stat="identity") + 
  scale_fill_manual(labels = c("Civil \nSociety", "Research &\nBusiness"), values = c("per_change_ci" = "#629074", "per_change_re" = "#b9c0f6")) +
           scale_y_continuous(labels = scales::percent, limits = c(-.40,.40))+
  labs(
    title = "Civil Society, Research & Business \nAuthored Courses by Capacity",
    subtitle = "% of change from United Nations level",
    x = "Sustainable Governance Capacities",
    y = NULL,
    fill = NULL
  ) + theme(legend.position = "none") + theme_minimal()
p4_c

```

```{r}
grid.arrange(p1_u, p2_g, nrow = 1)
grid.arrange(p3_u, p4_c, nrow = 1)



#final plot export for Figure 7. A
 ggsave(filename = "diagrams/figure7A.png", grid.arrange(p1_u, p2_g, nrow = 1) ,
       width = 10, height = 5, dpi = 300, units = "in", device='png')

```
```{r}
#final plot export for Figure 7. B
 ggsave(filename = "diagrams/figure7B.png", ggarrange(p3_u, p4_c, ncol=2, nrow=1, common.legend = FALSE, legend="bottom") ,
       width = 10, height = 5, dpi = 300, units = "in", device='png')
```

```{r}
# Make three plots.
# We set left and right margins to 0 to remove unnecessary spacing in the
# final plot arrangement.
p1 <- qplot(carat, price, data=dsamp, colour=clarity) +
   theme(plot.margin = unit(c(6,0,6,0), "pt"))
p2 <- qplot(depth, price, data=dsamp, colour=clarity) +
   theme(plot.margin = unit(c(6,0,6,0), "pt")) + ylab("")
p3 <- qplot(color, price, data=dsamp, colour=clarity) +
   theme(plot.margin = unit(c(6,0,6,0), "pt")) + ylab("")

# arrange the three plots in a single row
prow <- plot_grid( p1_u + theme(legend.position="none"),
           p2_g + theme(legend.position="none"),
           p3_u + theme(legend.position="none"),
           p4_c + theme(legend.position="none"),
           align = 'vh',
           labels = c("A", "B", "C", "D"),
           hjust = -1,
           nrow = 2
           )

# extract the legend from one of the plots
# (clearly the whole thing only makes sense if all plots
# have the same legend, so we can arbitrarily pick one.)
legend_b <- get_legend(p4_c + theme(legend.position="bottom"))

# add the legend underneath the row we made earlier. Give it 10% of the height
# of one plot (via rel_heights).
p <- plot_grid( prow, legend_b, ncol = 2, rel_heights = c(1, .2))
p
```

```{r}

all_courses_coded <- read_csv("data/final_coded_dataset.csv")
table(all_courses_coded$category)
#to long data
all_courses_coded_long <- all_courses_coded %>% 
  mutate(au_category = strsplit(as.character(au_category), ",")) %>%
  unnest(au_category)


#remove white spaces
all_courses_coded_long$au_category <- trimws(all_courses_coded_long$au_category)


all_courses_coded_long<- as.data.frame(all_courses_coded_long, headers=TRUE)

write.csv(all_courses_coded_long,"C:/Users/caitl/Documents/GitHub/mpp_thesis/exports/all_courses_coded_long.csv", row.names = TRUE)


#simply categories
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "cultural institution"] <- "civil society"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "ngo"] <- "civil society"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "business"] <- "research  business"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "finance"] <- "research  business"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "research  policy institutes"] <- "research  business"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "un ngo"] <- "civil society"

# add in un only courses

#au_diff_allcourses <- rbind(au_diff_main_long, au_diff_un_only)

```

```{r}
all_courses_coded <- read_csv("data/final_coded_dataset.csv")

#cleanup before plotting
all_courses_coded_long$category[all_courses_coded_long$category == "participation"] <- "Participation"
all_courses_coded_long$category[all_courses_coded_long$category == "policy coherence"] <- "Policy\nCoherence"
all_courses_coded_long$category[all_courses_coded_long$category == "democratic institutions"] <- "Democratic\nInstitutions"
all_courses_coded_long$category[all_courses_coded_long$category == "reflexivity and adaptation"] <- "Reflexivity &\nAdaptation"


all_courses_coded_long
all_courses_coded_long$category <- factor(all_courses_coded_long$category, levels = c("Participation", "Policy\nCoherence", "Democratic\nInstitutions", "Reflexivity &\nAdaptation"))
```

```{r}
#thanks to this guy: https://statsandr.com/blog/fisher-s-exact-test-in-r-independence-test-for-a-small-sample/

all_courses_coded_long <- read_csv("data/final_coded_dataset.csv")
```

```{r}
table(all_courses_coded$category)
#to long data
all_courses_coded_long <- all_courses_coded %>% 
  mutate(au_category = strsplit(as.character(au_category), ",")) %>%
  unnest(au_category)


#remove white spaces
all_courses_coded_long$au_category <- trimws(all_courses_coded_long$au_category)


all_courses_coded_long<- as.data.frame(all_courses_coded_long, headers=TRUE)

write.csv(all_courses_coded_long,"C:/Users/caitl/Documents/GitHub/mpp_thesis/exports/all_courses_coded_long.csv", row.names = TRUE)


#simply categories
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "cultural institution"] <- "civil society"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "ngo"] <- "civil society"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "business"] <- "research  business"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "finance"] <- "research  business"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "research  policy institutes"] <- "research  business"
all_courses_coded_long$au_category[all_courses_coded_long$au_category == "un ngo"] <- "civil society"

# add in un only courses

#au_diff_allcourses <- rbind(au_diff_main_long, au_diff_un_only)

#table 3. Contingency table
final_freq_table <- table(all_courses_coded_long$au_category, all_courses_coded_long$category)

chisq.test(final_freq_table)
```
```{r}
# Fisher's exact test
fishtest <- fisher.test(final_freq_table,simulate.p.value=TRUE,B=1e7)
fishtest

```

```{r}
#plot Figure 6. 

plot6<- ggbarstats(
  all_courses_coded_long, x = au_category, y = category,
  results.subtitle = FALSE,
  legend.title = "Author Stakeholder Group",
  subtitle = paste0(
    "Fisher's exact test", ", p-value = ",
    ifelse(fishtest$p.value < 0.001, "< 0.001", round(fishtest$p.value, 3))
  )
) + 
  scale_fill_manual(labels = c("UN", "Government","Public University","Private University","Civil Society", "Research & Business"),
    values = c(
      'un' = "#95ccba",
      'government' = "#e1b12d",
      'public university' = "#a7ba42",
      'private university' = "#a4d8ff",
      'civil society' = "#629074",
      'research  business' = "#b9c0f6")) +
  labs(
    title = "Multidisciplinary Authors of Sustainable Governance Capacities",
    subtitle = "for 211 training courses",
    x = "Sustainable Governance Capacities",
    y = "Author Group per Total Authors by Capacity",
    fill = "Author Group"
  ) + theme(legend.position = "none") + theme_minimal()  

plot6

 ggsave(filename = "diagrams/plot6.png", grid.arrange(plot6, nrow = 1) ,
       width = 10, height = 10, dpi = 300, units = "in", device='png')

```