---
title: "Tables for Paper"
author: "Caitlin Sarro"
date: "3/30/2022"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("groupdata2")

#stargazer
packages = c('tidyverse', 'tidytext', 'dplyr', 'ggplot2', 'table1', 'sjPlot','kableExtra')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}

```
```{r}
#tips to help remember: https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html

#import final data
final_coded_dataset <- read_csv("data/final/final_coded_dataset.csv")
```

```{r}

themes <- c("Participation", "Policy Coherence", "Democratic Institions", "Reflexivity & Adaptation")

examples <- c("Facilitation training to lead community meetings, bringing other groups on board", "Identifying inter-linkages between policies, aligning local and national policies", "Diplomatic training on negotiation, identifying trends to grow governmental transparency", "Analytical techniques and methodologies to increase program impact and SDG monitoring")

subthemes <- c("Increasing stakeholder engagement in SDG Governance", "Aligning to leverage synergies for SDG implementation", "Democracy increases social equity & access", "SDG goal setting to improve program delivery and measurement")

indicators <- c("* Stakeholder engagement\n  * Indigenous\n * Facilitation methods", "* Integrated planning \n * Horizontal alignment \n * Policy integration", "* Direct democracy \n * Governmental oversight \n * Diplomatic skills", "* Strategic planning \n * Evidence-based policy \n * Big data")

df <- data.frame(themes, examples, subthemes, indicators)


df %>%   
  kbl(caption = "Table 1. Sustainable Governance Capacities (Author defined)", col.names=c("Themes","Examples","Sub themes","Example indicators")) %>%
  kable_classic(full_width = F, html_font = "Open Sans") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"))%>%
  as_image(width = 8) %>%
  save_kable("diagrams/table1.pdf")


```


```{r}


criteria <- c("One Author Group", "Two Author Groups", "Three Author Groups", "Four Author Groups", "Five Author Groups", "Six Author Groups")

examples_2 <- c("Civil Society, Civil Society", "UN, Civil Society", "UN, Civil Society, Private University", "UN, Civil Society, Private University, Public University", "UN, Civil Society, Private University, Public University, Government", "UN, Civil Society, Private University, Public University, Government, Research & Business")

score <- c("1", "0.5", "0.33", "0.25", "0.2", "0.167")

df_2 <- data.frame(criteria, examples_2, score)


# Sample statistic health

table1::label(df_2$criteria) <- "Criteria" 
table1::label(df_2$examples_2) <- "Examples" 
table1::label(df_2$score) <- "Author Score for Civil Society" 
table_2 <- table1( ~ criteria + examples_2 + 
                     score, data = df_2)
table_2

```
```{r}
df_2 %>%
  kbl(col.names=linebreak(c('Criteria','Examples','Author Score for Civil Society'))) %>%
  kable_styling()
```
```{r}
df_2 %>%
  kbl(caption = "Table 2. Authors of Training Courses Weighted Coding Schema", col.names=c("Criteria","Examples","Score for\n Civil Society")) %>%
   column_spec(column = 1, width = "1in")  %>%
   column_spec(column = 2, width = "3.5in") %>%
   column_spec(column = 3, width = ".75in") %>%
  kable_classic(full_width = F, html_font = "Open Sans") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"))


```


```{r}
#table 4
tb4_part <- c("15.2%", "(16)", "31.7%", "(9)", "↑ 16.4%")
tb4_pol <- c("13.3%", "(14)", "20.1%", "(6)", "↑ 6.8%")
tb4_dem <- c("26.7%", "(28)", "27.4%", "(10)", "↑ 0.7%")
tb4_ref <- c("44.8%", "(47)", "20.9%", "(6)", "↓ -23.9%")

table4 <- rbind(tb4_part,tb4_pol,tb4_dem,tb4_ref)
table4
rownames(table4) <- c("Participation","Policy\nCoherence","Democratic\nInstitutions","Reflexivity & \n Adaptation")
colnames(table4) <- c("UN Only \n Authored Trainings","(N=105)","UN Partnered with\nother Stakeholder Authors","weighted\n(N= 31)","% Change")


table4 %>%
  kbl(caption = "Table 4. Sustainable Governance Capacities for trainings by UN Author Groups") %>%
   column_spec(column = 1, width = ".35in")  %>%
   column_spec(column = 2, width = ".35in") %>%
   column_spec(column = 3, width = ".35in") %>%
   column_spec(column = 4, width = ".55in") %>%
   column_spec(column = 5, width = ".35in") %>%
  kable_classic(html_font = "Open Sans") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = FALSE) %>%
  save_kable(file = 'diagrams/table4.png')
```
```{r}
#table 6
UN Aggregate	public university	private university	civil society	business/finance/research	government
19	5	4	4	4	2
16	4	3	2	1	2
31	9	7	3	8	2
49	9	2	3	8	13



tb6_part <- c("19 (16.8%)", "5 (20.0%)", "4 (26.1%)", "4 (12.6%)", "4 (19.6%)", " 2 (37.1%)")
tb6_pol <- c("16 (14.0%)", "4 (15.2%)", "3 (17.1%)", "2 (11.3%)", "1 (5.6%)", "2 (13.8%)")
tb6_dem <- c("31 (26.7%)", "9 (32.9%)", "7 (42.4%)", "3 (8.3%)", "8 (36.5%)", "2 (26.4%)")
tb6_ref <- c("49 (42.5%)", "9 (31.9%)", "2 (14.4%)", "3 (67.8%)", "8 (38.3%)", "13 (22.7%)")

table6 <- rbind(tb6_part,tb6_pol,tb6_dem,tb6_ref)
table6
rownames(table6) <- c("Participation","Policy\nCoherence","Democratic\nInstitutions","Reflexivity & \n Adaptation")
colnames(table6) <- c("UN Aggregate","Public University","Private University","Government","Research & Business","Civil Society")


table6 %>%
  kbl(caption = "Table 6. Summary Distribution of 211 training courses across Sustainable Governance Capacities and Authors") %>%
   column_spec(column = 1, width = "0.55 in")  %>%
   column_spec(column = 2, width = ".75 in") %>%
   column_spec(column = 3, width = ".35in") %>%
   column_spec(column = 4, width = ".55in") %>%
   column_spec(column = 5, width = ".35in") %>%
   column_spec(column = 6, width = ".35in") %>%
  kable_classic(html_font = "Open Sans") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), full_width = FALSE) 

#%>% save_kable(file = 'diagrams/table6.png')
```


```{r}
kbl(df_2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))



```


```{r}
#Table 3. Contingency Table
freq_table <- read_csv("exports/final_freq_table.csv")
freq_table



freq_table %>%
  kbl(caption = "Table 3. Authors of Training Courses by Goverance Category", col.names=c("Civil Society","Government","Private University","Public University","Research & Business","UN"))%>%
   column_spec(column = 1, width = ".35in")  %>%
   column_spec(column = 2, width = ".35in") %>%
   column_spec(column = 3, width = ".35in") %>%
   column_spec(column = 4, width = ".55in") %>%
   column_spec(column = 5, width = ".35in") %>%
   column_spec(column = 6, width = ".35in") %>%
   column_spec(column = 7, width = ".35in") %>%
  kable_classic(full_width = FALSE, html_font = "Open Sans") %>%
  kable_styling(bootstrap_options = c("striped", "condensed"))

freq_table <- table(final_coded_dataset$category, final_coded_dataset$au_category)
chisq.test(freq_table)$expected
final_coded_dataset
#"Sustainable Governance Category",
```
